;;; private/misc-applications/autoload/disk-usage.el -*- lexical-binding: t; -*-

;;;###autoload (autoload '+disk-usage-hydra/body "private/misc-applications/autoload/disk-usage" nil t)
(defhydra +disk-usage-hydra (:color pink :hint nil)
  ("<f6>" nil "Exit" :exit t)
  ("q" quit-window nil :exit t)
  ("A" disk-usage-remove-filters "Remove filters" :column "Filters")
  ("R" disk-usage-toggle-recursive "Toggle hierarchical view" :column "Display")
  ("^" disk-usage-up "Run on parent directory" :column "Misc")
  ("a" disk-usage-add-filters "Add filters" :column "Filters")
  ("d" disk-usage-dired-at-point "Dired" :column "Act" :exit t)
  ("e" disk-usage-eshell-at-point "Eshell" :column "Act" :exit t)
  ("S-<return>" disk-usage-find-file-at-point "Find file" :column "Act" :exit t)
  ("f" disk-usage-toggle-full-path "Toggle full path" :column "Display")
  ("S" tabulated-list-sort "Sort" :column "Display")
  ("g" revert-buffer "Refresh" :column "Display")
  ("m" disk-usage-mark "Mark" :column "Mark")
  ("u" disk-usage-unmark "Unmark" :column "Mark")
  ("x" disk-usage-delete-marked-files "Delete marked files" :column "Act"))
