# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export PATH=~/.local/bin:$PATH

alias cp="cp --reflink=auto --sparse=auto"
alias ls="sudo ls --color=auto --group-directories-first"
alias la="sudo ls -A"
alias l="sudo ls -A"
alias ll="sudo ls -lh"
alias lla="sudo ll -A"
alias gr="sudo egrep -s --colour=auto"
alias t="sudo tree -C"
alias t1="sudo t -L 1"
alias t2="sudo t -L 2"
alias f="sudo find"
alias doom="~/.emacs.d/bin/doom"
alias sysu="systemctl --user"
alias sysur="systemctl --user restart"
alias sysux="systemctl --user stop"
alias sysus="systemctl --user start"
alias sysut="systemctl --user status"
alias sysue="systemctl --user enable"
alias sys="sudo systemctl"
alias sysr="sudo systemctl restart"
alias sysx="sudo systemctl stop"
alias syst="sudo systemctl status"
alias syss="sudo systemctl start"
alias syse="sudo systemctl enable"
alias log="journalctl"
alias dmesg="dmesg -HP"
alias grep="grep --color=auto"
alias c="xsel --clipboard"
alias weather="curl wttr.in"
alias sl="sudo ls"
alias exi="exit"
alias cryptsetup="sudo cryptsetup"
alias sysctl="sudo sysctl"
alias mount="sudo mount"
alias vgchange="sudo vgchange"
alias eject="sudo eject"
alias fdisk="sudo fdisk"
alias update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg"

function swap()
{
    local TMPFILE=tmp.$$
    mv "$1" $TMPFILE && mv "$2" "$1" && mv $TMPFILE "$2"
}

export NIXPKGS_ALLOW_INSECURE=1
export DTK_PROGRAM
DTK_PROGRAM=espeak

if [[ ! -d ~/.zsh-autopair ]]; then
  git clone https://github.com/hlissner/zsh-autopair ~/.zsh-autopair
fi

source ~/.zsh-autopair/autopair.zsh
autopair-init

if [[ -z ${DBUS_SESSION_BUS_ADDRESS} ]]; then
	if [[ -f ~/.dbus/session-bus/$(dbus-uuidgen --get)-0 ]]; then
		source ~/.dbus/session-bus/$(dbus--uuidgen --get)-0
		export DBUS_SESSION_BUS_ADDRESS
	fi
fi

export KALEIDOSCOPE_DIR=${HOME}/src/Kaleidoscope

#export NO_AT_BRIDGE=1

# Local Variables:
# eval: (call-interactively #'shell-script-mode)
# End:
