;;; private/misc-applications/eaf.el -*- lexical-binding: t; -*-

;;(require 'eaf-music-player)
;;(require 'eaf-video-player)
;;(require 'eaf-js-video-player)
;;(require 'eaf-image-viewer)
;;(require 'eaf-rss-reader)
;;(require 'eaf-terminal)
;;(require 'eaf-markdown-previewer)
;;(require 'eaf-org-previewer)
;;(require 'eaf-camera)
;;(require 'eaf-git)
;;(require 'eaf-file-manager)
;;(require 'eaf-mindmap)
;;(require 'eaf-netease-cloud-music)
;;(require 'eaf-system-monitor)
;;(require 'eaf-file-browser)
;;(require 'eaf-file-sender)
;;(require 'eaf-airshare)
;;(require 'eaf-jupyter)
;;(require 'eaf-2048)
;;(require 'eaf-markmap)
;;(require 'eaf-map)
;;(require 'eaf-demo)
;;(require 'eaf-vue-demo)
;;(require 'eaf-vue-tailwindcss)
;;(require 'eaf-pyqterminal)
